[ffmpeg]
url = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z"
archive_name = "ffmpeg-git-essentials.7z"
directory = "ffmpeg"
executable = "ffmpeg.exe"

[youtube]
video_urls = [
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "https://www.youtube.com/watch?v=jNQXAC9IVRw"
]

[youtube-playlist]
playlist_url = "https://www.youtube.com/playlist?list=PLExamplePlaylistId"

[output]
directory = "D:\\MP3"
